"""add isbn and image_url

Revision ID: 888e7a91a74f
Revises: aa8c489f0972
Create Date: 2026-05-13 07:34:30.967278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888e7a91a74f'
down_revision: Union[str, None] = 'aa8c489f0972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    op.add_column('books', sa.Column('img_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_column('books', 'img_url')
    op.drop_column('books', 'isbn')
    # ### end Alembic commands ###
