"""ADD created_at to books

Revision ID: aa8c489f0972
Revises: 34a54357f5da
Create Date: 2026-01-15 07:50:17.121739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa8c489f0972'
down_revision: Union[str, None] = '34a54357f5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('books', sa.Column('create_date', sa.DateTime(timezone=True), nullable=True))

    op.execute("UPDATE books SET create_date = CURRENT_TIMESTAMP WHERE create_date IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'create_date')
    # ### end Alembic commands ###
